''' <summary>
''' This class stores and structures the data contained in RFIs. 
''' Will be displayed in the RFI display in Form2, constructor will be run after Form3 submits.
''' Stored in a list of rfiClass objects and then gets exported to a .RFI (XML) File. 
''' </summary>
''' 


Public Class rfiClass
    ' Properties to store the RFI data behind the scenes.
    Private Property _ID As Integer = -1 ' ID of rfi, validated on input into the class, no within the class. Defaults to -1 to detect any errors when using the class
    Private Property _desc As String = "" ' Long description entered by user
    Private Property _descAI As String = "" ' Short description generated by AI by the generateShortDesc function
    Private Property _imgLoc As String = "" ' Location of the image, will likely be stored in the project file
    Private Property _isComplete As Boolean = False ' Stores whether it has been completed yet, defaults to false
    Private Property _dateCreated As DateTime = DateTime.MinValue ' stores when the class was created, defaults to a dummy value indicating not created yet
    Private Property _dateCompleted As DateTime = DateTime.MinValue ' this stores when the class was marked completed when completeRFI is ran. Defaults to a default dummy value indicating not completed yet
    Private Property _daysPast As Integer = -1 ' Set to -1 to detect if we have calculated yet.


    ' Public getters and setters for private properties to meet requirement
    Public ReadOnly Property ID As Integer ' readonly for clarity that this should not be changed after creation as it correlates to emails and other documents.
        Get
            Return _ID
        End Get
    End Property

    Public Property desc As String ' access to change desc for editing
        Get
            Return _desc
        End Get
        Set(value As String)
            _desc = value
        End Set
    End Property

    Public Property descAI As String ' access to change descAI for editing, as this is generated by the AI and very likely will be edited
        Get
            Return _descAI
        End Get
        Set(value As String)
            _descAI = value
        End Set
    End Property

    Public Property imgLoc As String ' access to change imgLoc for editing, as this is likely to be changed by the user if the image is moved
        Get
            Return _imgLoc
        End Get
        Set(value As String)
            _imgLoc = value
        End Set
    End Property
    Public Property isComplete As Boolean ' access to change isComplete for editing, as this will be changed in normal use.
        Get
            Return _isComplete
        End Get
        Set(value As Boolean)
            _isComplete = value
        End Set
    End Property

    Public ReadOnly Property dateCreated As DateTime ' Autogenerated upon creation, does not need to be changed so readonly for clarity.
        Get
            Return _dateCreated
        End Get
    End Property

    Public Property dateCompleted As DateTime ' Access to change dateCompleted for editing, as this will be changed when the RFI is marked as completed and may want to be changed.
        Get
            Return _dateCompleted
        End Get
        Set(value As DateTime)
            _dateCompleted = value
        End Set
    End Property

    Public ReadOnly Property daysPast As Integer ' readonly as its calculated as a maths function of dateCreated and dateCompleted, so should not be changed by the user.
        Get
            If _daysPast <> -1 Then ' If it has been calculated, return the value
                Return _daysPast
            Else ' If it has not been calculated, calculate it now.
                _daysPast = (DateTime.Now - _dateCreated).Days ' Calculate days past since creation
                Return _daysPast
            End If
        End Get
    End Property

    Private Const AIPrompt As String = "<prompt>summarize the following description to 15 words, make sure to include ALL important information</prompt>" ' Private constant AI prompt to avoid having it inline in the function.
    ''' <summary>
    ''' Constructor for the rfiClass, initializes the RFI with an ID, description, and image location.
    ''' </summary>
    ''' <param name="ID">Unique identifier for the RFI</param>
    ''' <param name="desc">Description of the RFI</param>
    ''' <param name="image">Location of the image associated with the RFI</param>
    Public Sub New(ID As Integer, desc As String, image As String)
        ' Set inital variables
        _ID = ID
        _desc = desc
        _imgLoc = image
        _dateCreated = DateTime.Now
    End Sub

    ''' <summary>
    ''' Constructor for the rfiClass, initializes the RFI with all properties.
    ''' This constructor is used when loading from XML.
    ''' </summary>
    ''' <param name="id"></param>
    ''' <param name="desc"></param>
    ''' <param name="descAI"></param>
    ''' <param name="imgLoc"></param>
    ''' <param name="isComplete"></param>
    ''' <param name="dateCreated"></param>
    ''' <param name="dateCompleted"></param>
    ''' <param name="daysPast"></param>
    Public Sub New(id As Integer, desc As String, descAI As String, imgLoc As String, isComplete As Boolean, dateCreated As DateTime, dateCompleted As DateTime, daysPast As Integer)
        _ID = id
        _desc = desc
        _descAI = descAI
        _imgLoc = imgLoc
        _isComplete = isComplete
        _dateCreated = dateCreated
        _dateCompleted = dateCompleted
        _daysPast = daysPast
    End Sub

    Public Sub completeRFI()
        ' Mark the RFI as complete and set the completion date
        _isComplete = True
        _dateCompleted = DateTime.Now
        _daysPast = (DateTime.Now - _dateCreated).Days ' Calculate days past since creation
    End Sub
End Class


Public Class projectClass
    Public Property rfiList As New List(Of rfiClass) ' public and not through getters and setters to make sure users of the class have access to all list functions

    Public Sub exportXML()
        For Each rfi As rfiClass In rfiList

        Next
    End Sub


    Public Sub loadXML(rfiXML As XDocument)
        For Each RFI As XElement In rfiXML.Root.Elements("rfi")

        Next
    End Sub
End Class